version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Instalando las dependencias necesarias"
  pre_build:
    commands:
      - echo "Restaurando las dependencias del proyecto..."
      - dotnet restore BlackListApi/BlackListApi/BlackListApi.csproj
  build:
    commands:
      - echo "Compilando la aplicación..."
      - dotnet build BlackListApi/BlackListApi/BlackListApi.csproj --configuration Release
  post_build:
    commands:
      - echo "Ejecutando las pruebas..."
      - dotnet test BlackListApi/Tests/Tests.csproj --configuration Release
      - echo "Generando archivos de publicación..."
      - dotnet publish BlackListApi/BlackListApi/BlackListApi.csproj --configuration Release -o output/publish
      - echo "Construyendo la imagen del contenedor..."
      - echo "Generando la imagen con tag = latest"
      - docker build -t 529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest -f BlackListApi/Dockerfile.ci .
      - echo "Pushing la imagen al repositorio ECR aws..."
      - docker push  529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest
      
artifacts:
  files:
    - '**/bin/Release/net8.0/publish/**/*'
  discard-paths: yes
  name: fcamilob/blacklistapi:$CODEBUILD_BUILD_NUMBER

cache:
  paths:
    - '**/obj/**'
    - '**/bin/**'

