name: "Build And Test"

on:
  push:
 
permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net Core 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./BlackListApi/BlackListApi.sln

      - name: Build
        run: dotnet build ./BlackListApi/BlackListApi.sln --configuration Release --no-restore 

      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore --logger "trx;LogFileName=test-results.xml"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'Unit Tests'
          path: '**/test-results.xml'
          reporter: 'dotnet-trx'
        
